spring:
  application:
    name: audition-api
  config:
    import: "optional:configserver:"
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  mvc:
    throw-exception-if-no-handler-found: true
  sleuth:
    sampler:
      probability: 1.0
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=5m,expireAfterAccess=2m,recordStats

server:
  max-http-request-header-size: 16KB
  port: 8080
  servlet:
    context-path: /api/v1
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  error:
    include-stacktrace: never
    include-message: always
    include-binding-errors: never

# Application-specific configuration
audition:
  external-apis:
    jsonplaceholder:
      base-url: ${JSONPLACEHOLDER_BASE_URL:https://jsonplaceholder.typicode.com}
      timeout: ${EXTERNAL_API_TIMEOUT:30000}
      retry-attempts: ${RETRY_ATTEMPTS:3}
      circuit-breaker-enabled: ${CIRCUIT_BREAKER_ENABLED:true}
  caching:
    enabled: ${CACHING_ENABLED:true}
    ttl-minutes: ${CACHE_TTL_MINUTES:5}
    max-size: ${CACHE_MAX_SIZE:1000}

# Management and monitoring
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,metrics,prometheus,caches
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
      probes:
        enabled: true
    info:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
    caches:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
      slo:
        http.server.requests: 100ms,200ms,500ms,1s,2s
    tags:
      application: ${spring.application.name}
      version: ${audition.version:unknown}
      environment: ${ENVIRONMENT:dev}

# Logging configuration
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:-%5p} [%thread] %logger{36} - %msg%n"
  level:
    com.audition: INFO
    org.springframework.web: INFO
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.cache: DEBUG
    org.springframework.security: WARN
    org.hibernate: WARN
    io.micrometer: INFO
    brave: WARN
    io.github.resilience4j: INFO

# Resilience4j configuration
resilience4j:
  circuitbreaker:
    instances:
      jsonplaceholder:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        record-exceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.ResourceAccessException
  retry:
    instances:
      jsonplaceholder:
        max-attempts: 3
        wait-duration: 1s
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.ResourceAccessException
        ignore-exceptions:
          - com.audition.common.exception.SystemException
  timelimiter:
    instances:
      jsonplaceholder:
        timeout-duration: 10s

# Security settings
security:
  headers:
    frame-options: DENY
    content-type-options: nosniff
    xss-protection: "1; mode=block"
    referrer-policy: strict-origin-when-cross-origin
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,https://yourdomain.com}
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600

# API Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
  info:
    title: Audition API
    description: API for managing posts and comments
    version: 1.0.0
    contact:
      name: API Support
      email: support@audition.com

---
# Development profile
spring:
  config:
    activate:
      on-profile: dev
  sleuth:
    sampler:
      probability: 1.0

logging:
  level:
    com.audition: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.cache: DEBUG
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*" # Expose all endpoints in dev

audition:
  external-apis:
    jsonplaceholder:
      base-url: https://jsonplaceholder.typicode.com
      timeout: 10000

resilience4j:
  circuitbreaker:
    instances:
      jsonplaceholder:
        failure-rate-threshold: 80 # More lenient in dev
        wait-duration-in-open-state: 10s

---
# Production profile
spring:
  config:
    activate:
      on-profile: prod
  sleuth:
    sampler:
      probability: 0.1 # Reduced sampling in production

logging:
  level:
    com.audition: INFO
    org.springframework.web.client.RestTemplate: WARN
    org.springframework.cache: WARN
    root: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus # Limited endpoints in prod

audition:
  external-apis:
    jsonplaceholder:
      base-url: ${JSONPLACEHOLDER_BASE_URL:https://jsonplaceholder.typicode.com}
      timeout: 5000

resilience4j:
  circuitbreaker:
    instances:
      jsonplaceholder:
        failure-rate-threshold: 30 # Strict in production
        wait-duration-in-open-state: 60s

---
# Test profile
spring:
  config:
    activate:
      on-profile: test
  sleuth:
    enabled: false
  cache:
    type: simple # Use simple cache for tests

management:
  tracing:
    enabled: false

audition:
  caching:
    enabled: false # Disable caching in tests for predictable behavior

resilience4j:
  circuitbreaker:
    instances:
      jsonplaceholder:
        sliding-window-size: 5
        minimum-number-of-calls: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s